// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "bc3f90de-0e4d-4303-9131-155e57257ff7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onVoltageChange();
void onLedSwitchChange();
void onLedChange();
void onStatusChange();
void onUnderVoltChange();

float voltage;
bool led_switch;
bool led;
bool status;
bool under_volt;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(voltage, READWRITE, 1 * SECONDS, onVoltageChange);
  ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange);
  ArduinoCloud.addProperty(led, READWRITE, 1 * SECONDS, onLedChange);
  ArduinoCloud.addProperty(status, READWRITE, 1 * SECONDS, onStatusChange);  
  ArduinoCloud.addProperty(under_volt, READWRITE, ON_CHANGE, onUnderVoltChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
